Revert "[mesa-git] Test enable rusticl."
We're not there yet. Fails with compile errors

error[E0412]: cannot find type `cache_key` in this scope
  --> ../src/gallium/frontends/rusticl/mesa/util/disk_cache.rs:25:46
   |
25 |     pub fn put(&self, data: &[u8], key: &mut cache_key) {
   |                                              ^^^^^^^^^ not found in this scope

error[E0412]: cannot find type `cache_key` in this scope
  --> ../src/gallium/frontends/rusticl/mesa/util/disk_cache.rs:37:33
   |
37 |     pub fn get(&self, key: &mut cache_key) -> Option<DiskCacheEntry> {
   |                                 ^^^^^^^^^ not found in this scope
...
...
...

This reverts commit d81a1976604aecb4e2646af31e94ba30c62f694b.